### ISSUE TITLE
As a user, I want to email my contacts

### ISSUE THREAD

**Issue by awarenessxz** [CS2103AUG2017-W14-B2/main#61]
...so that I can keep in touch with them

- [x] Email using JavaMail API #62 
- [x] Create LoginEmail class to handle Email Logins #80 
- [x] Create sendEmail class to handle sending Emails #81
- [x] Create composeMessage class to handle Email Drafts #82 
- [x] Display email in GUI before email is sent #63 
- [x] Clear email Draft in GUI #128 
- [ ] Using User Config to Store Login Details #64 
- [ ] Accepting Break lines in Email messages #65 
- [ ] Emailing of attachments #66
- [ ] Create multiple email drafts #76  
- [ ] Enhanced app security #77
